default_language_version:
  python: python3.13
default_stages: [pre-commit, pre-push]
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.8
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: local
  hooks:
  - id: unit-tests
    name: unit-tests
    entry: test.sh
    language: script
    pass_filenames: false
